version: '3'
services:
    jenkins-docker-compose:
        build: .
        image: jenkins-docker-compose:latest
        ports:
            - 58080:8080
            - 50000:50000
        volumes:
            - /var/jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
